// Copyright Eagle Legacy Modernization LLC, 2010-date
// Original author: Steven A. O'Hara, Jul 21, 2024

package com.eagle.programmar.Rust;

public class Rust_Reserved_Words
{
	// From https://doc.rust-lang.org/reference/keywords.html
	public static final String[] RESERVED_WORDS = new String[] {
			"Self",
			"abstract",
			"as",
			"as_str",
			"async",
			"await",
			"become",
			"box",
			"break",
			"const",
			"continue",
			"crate",
			"do",
			"dyn",
			"else",
			"enum",
			"extern",
			"false",
			"final",
			"fn",
			"for",
			"format",
			"if",
			"impl",
			"in",
			"len",
			"let",
			"loop",
			"macro",
			"match",
			"mod",
			"move",
			"mut",
			"override",
			"println",
			"priv",
			"pub",
			"ref",
			"return",
			"rev",
			"self",
			"starts_with",
			"static",
			"struct",
			"super",
			"to_string",
			"trait",
			"true",
			"try",
			"type",
			"typeof",
			"unsafe",
			"unsized",
			"use",
			"virtual",
			"where",
			"while",
			"yield",
	};
}
