// Copyright Eagle Legacy Modernization LLC, 2010-date
// Original author: Steven A. O'Hara, Sep 30, 2012

package com.eagle.programmar.SQL;

import com.eagle.core.EagleSyntax;
import com.eagle.programmar.SQL.Terminals.SQL_Comment;

public class SQL_Syntax extends EagleSyntax
{
	@Override
	public String syntaxId()
	{
		return "SQL";
	}
	
	public SQL_Syntax()
	{
		_isCaseSensitive = false;
		_continuationChar = null;
		_extraCharacters = "_";
		_commentInstance = new SQL_Comment();
		_punctuationExceptions = new String[] { "!=", "<=", "==", ">=", "=>", "||", "&&", "/*" };
		
		addReservedWords(reservedWords);
	}

	// https://www.ibm.com/docs/en/psfa/7.2.1?topic=keywords-sql-common-reserved-words
	private static String[] reservedWords = new String[]
	{
			"ABORT",
			"ALL",
			"ALLOCATE",
			"ANALYSE",
			"ANALYZE",
			"AND",
			"ANY",
			"AS",
			"ASC",
			"BETWEEN",
			"BINARY",
			"BIT",
			"BOTH",
			"CASE",
			"CAST",
			"CHAR",
			"CHARACTER",
			"CHECK",
			"CLUSTER",
			"COALESCE",
			"COLLATE",
			"COLLATION",
			"COLUMN",
			"CONSTRAINT",
			"COPY",
			"CROSS",
			"CURRENT",
			"CURRENT_CATALOG",
			"CURRENT_DATE",
			"CURRENT_DB",
			"CURRENT_SCHEMA",
			"CURRENT_SID",
			"CURRENT_TIME",
			"CURRENT_TIMESTAMP",
			"CURRENT_USER",
			"CURRENT_USERID",
			"CURRENT_USEROID",
			"DEALLOCATE",
			"DEC",
			"DECIMAL",
			"DECODE",
			"DEFAULT",
			"DESC",
			"DISTINCT",
			"DISTRIBUTE",
			"DO",
			"ELSE",
			"END",
			"EXCEPT",
			"EXCLUDE",
			"EXISTS",
			"EXPLAIN",
			"EXPRESS",
			"EXTEND",
			"EXTERNAL",
			"EXTRACT",
			"FALSE",
			"FIRST",
			"FLOAT",
			"FOLLOWING",
			"FOR",
			"FOREIGN",
			"FROM",
			"FULL",
			"FUNCTION",
			"GENSTATS",
			"GLOBAL",
			"GROUP",
			"HAVING",
			"IDENTIFIER_CASE",
			"ILIKE",
			"IN",
			"INDEX",
			"INITIALLY",
			"INNER",
			"INOUT",
			"INTERSECT",
			"INTERVAL",
			"INTO",
			"LEADING",
			"LEFT",
			"LIKE",
			"LIMIT",
			"LOAD",
			"LOCAL",
			"LOCK",
			"MINUS",
			"MOVE",
			"NATURAL",
			"NCHAR",
			"NEW",
			"NOT",
			"NOTNULL",
			"NULL",
			"NULLS",
			"NUMERIC",
			"NVL",
			"NVL2",
			"OFF",
			"OFFSET",
			"OLD",
			"ON",
			"ONLINE",
			"ONLY",
			"OR",
			"ORDER",
			"OTHERS",
			"OUT",
			"OUTER",
			"OVER",
			"OVERLAPS",
			"PARTITION",
			"POSITION",
			"PRECEDING",
			"PRECISION",
			"PRESERVE",
			"PRIMARY",
			"RESET",
			"RESET",
			"REUSE",
			"REUSE",
			"RIGHT",
			"ROWS",
			"SELECT",
			"SESSION_USER",
			"SETOF",
			"SHOW",
			"SOME",
			"TABLE",
			"THEN",
			"TIES",
			"TIME",
			"TIMESTAMP",
			"TO",
			"TRAILING",
			"TRANSACTION",
			"TRIGGER",
			"TRIM",
			"TRUE",
			"UNBOUNDED",
			"UNION",
			"UNIQUE",
			"USER",
			"USING",
			"VACUUM",
			"VARCHAR",
			"VERBOSE",
			"VERSION",
			"VIEW",
			"WHEN",
			"WHERE",
			"WITH",
			"WRITE",
	};
}
