// Copyright Eagle Legacy Modernization, 2010-date
// Original author: Steven A. O'Hara, Dec 7, 2010

package com.eagle.programmar.COBOL;

import com.eagle.programmar.COBOL.Statements.COBOL_AcceptStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_AddStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_CallStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_CancelStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_CloseStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_CommitStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_ComputeStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_ContinueStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_CopyStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_DeleteStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_DisplayStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_DivideStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_EvaluateStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_ExitStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_GenerateStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_GoBackStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_GoStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_IfStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_InitializeStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_InitiateStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_InspectStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_InvokeStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_MergeStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_MoveStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_MultiplyStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_NextStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_OpenStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_PerformStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_ReadStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_ReleaseStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_ReturnStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_RewriteStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_SearchStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_SetStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_SortStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_StartStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_StopStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_StringStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_SubtractStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_TerminateStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_UnlockStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_UnstringStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_UseStatement;
import com.eagle.programmar.COBOL.Statements.COBOL_WriteStatement;
import com.eagle.tokens.TokenChooser;
import com.eagle.tokens.interfaces.AbstractStatement;

public class COBOL_Statement extends TokenChooser implements AbstractStatement
{
	public @CHOICE COBOL_AcceptStatement XXacceptStatement;
	public @CHOICE COBOL_AddStatement XXaddStatement;
	public @CHOICE COBOL_CallStatement XXcallStatement;
	public @CHOICE COBOL_CancelStatement XXcancelStatement;
	public @CHOICE COBOL_CloseStatement XXcloseStatement;
	public @CHOICE COBOL_CommitStatement XXcommitStatement;
	public @CHOICE COBOL_ComputeStatement XXcomputeStatement;
	public @CHOICE COBOL_ContinueStatement XXcontinueStatement;
	public @CHOICE COBOL_CopyStatement XXcopyStatement;
	public @CHOICE COBOL_DeleteStatement XXdeleteStatement;
	public @CHOICE COBOL_DisplayStatement XXdisplayStatement;
	public @CHOICE COBOL_DivideStatement XXdivideStatement;
	public @CHOICE COBOL_ExitStatement XXexitStatement;
	public @CHOICE COBOL_EvaluateStatement XXevaluateStatement;
	public @CHOICE COBOL_GenerateStatement XXgenerateStatement;
	public @CHOICE COBOL_GoStatement XXgoStatement;
	public @CHOICE COBOL_GoBackStatement XXgoBackStatement;
	public @CHOICE COBOL_IfStatement XXifStatement;
	public @CHOICE COBOL_InitiateStatement XXinitiateStatement;
	public @CHOICE COBOL_InitializeStatement XXinitializeStatement;
	public @CHOICE COBOL_InvokeStatement XXinvokeStatement;
	public @CHOICE COBOL_InspectStatement XXinspectStatement;
	public @CHOICE COBOL_MergeStatement XXmergeStatement;
	public @CHOICE COBOL_MoveStatement XXmoveStatement;
	public @CHOICE COBOL_MultiplyStatement XXmultiplyStatement;
	public @CHOICE COBOL_NextStatement XXnextStatement;
	public @CHOICE COBOL_OpenStatement XXopenStatement;
	public @CHOICE COBOL_PerformStatement XXperformStatement;
	public @CHOICE COBOL_ReadStatement XXreadStatement;
	public @CHOICE COBOL_ReleaseStatement XXreleaseStatement;
	public @CHOICE COBOL_ReturnStatement XXreturnStatement;
	public @CHOICE COBOL_RewriteStatement XXrewruteStatement;
	public @CHOICE COBOL_SearchStatement XXsearchStatement;
	public @CHOICE COBOL_SetStatement XXsetStatement;
	public @CHOICE COBOL_SortStatement XXsortStatement;
	public @CHOICE COBOL_StartStatement XXstartStatement;
	public @CHOICE COBOL_StopStatement XXstopStatement;
	public @CHOICE COBOL_StringStatement XXstringStatement;
	public @CHOICE COBOL_SubtractStatement XXsubtractStatement;
	public @CHOICE COBOL_TerminateStatement XXterminateStatement;
	public @CHOICE COBOL_UnlockStatement XXunlockStatement;
	public @CHOICE COBOL_UnstringStatement XXunstringStatement;
	public @CHOICE COBOL_UseStatement XXuseStatement;
	public @CHOICE COBOL_WriteStatement XXwriteStatement;

	// public @LAST COBOL_UnparsedStatement XXunparsedStatement;
}
