// Copyright Eagle Legacy Modernization LLC, 2010-date
// Original author: Steven A. O'Hara, Jul 21, 2024

package com.eagle.programmar.Ada;

public class Ada_Reserved_Words
{
	// From
	// https://www.adaic.org/resources/add_content/standards/05rm/html/RM-2-9.html
	public static final String[] RESERVED_WORDS = new String[] {
			"abort",
			"abs",
			"abstract",
			"accept",
			"access",
			"aliased",
			"all",
			"and",
			"array",
			"at",
			"begin",
			"body",
			"case",
			"constant",
			"declare",
			"delay",
			"delta",
			"digits",
			"do",
			"else",
			"elsif",
			"end",
			"entry",
			"exception",
			"exit",
			"for",
			"function",
			"generic",
			"goto",
			"if",
			"in",
			"interface",
			"is",
			"limited",
			"loop",
			"mod",
			"new",
			"not",
			"null",
			"of",
			"or",
			"others",
			"out",
			"overriding",
			"package",
			"pragma",
			"private",
			"procedure",
			"protected",
			"put",
			"put_line",
			"raise",
			"range",
			"record",
			"rem",
			"renames",
			"requeue",
			"return",
			"reverse",
			"select",
			"separate",
			"subtype",
			"synchronized",
			"tagged",
			"task",
			"terminate",
			"then",
			"type",
			"until",
			"use",
			"when",
			"while",
			"with",
			"xor",
	};
}
