// Copyright Eagle Legacy Modernization LLC, 2010-date
// Original author: Steven A. O'Hara, Jul 21, 2024

package com.eagle.programmar.Delphi;

public class Delphi_Reserved_Words
{
	// From https://en.wikibooks.org/wiki/Delphi_Programming/Reserved_keywords
	public static final String[] RESERVED_WORDS = new String[] {
			"and",
			"array",
			"as",
			"asm",
			"begin",
			"case",
			"class",
			"const",
			"constructor",
			"destructor",
			"dispinterface",
			"div",
			"do",
			"downto",
			"else",
			"end",
			"except",
			"exports",
			"file",
			"finalization",
			"finally",
			"for",
			"function",
			"goto",
			"if",
			"implementation",
			"in",
			"inherited",
			"initialization",
			"inline",
			"interface",
			"is",
			"label",
			"library",
			"mod",
			"nil",
			"not",
			"object",
			"of",
			"or",
			// "out", // Not really reserved. And often used.
			"packed",
			"procedure",
			"program",
			"property",
			"raise",
			"record",
			"repeat",
			"resourcestring",
			"set",
			"shl",
			"shr",
			"string",
			"then",
			"threadvar",
			"to",
			"try",
			"type",
			"unit",
			"until",
			"uses",
			"var",
			"while",
			"with",
			"xor",
	};
}
